version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.9.5
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

prepare_tox: &prepare_tox
  run:
    name: Install tox
    command: |
      sudo pip install --upgrade pip
      pip install --user tox

fetch_data: &fetch_data
  run:
    name: Set script permissions and fetch data
    command: |
      source venv/bin/activate
      chmod +x ./scripts/fetch_kaggle_dataset.sh
      ./scripts/fetch_kaggle_dataset.sh

jobs:
  test_app:
    <<: *defaults
    working_directory: ~/project
    steps:
      - checkout:
          path: ~/project
      - *prepare_tox
      - run:
          name: Runnning app tests
          command: |
            tox

  deploy_app_to_heroku:
    <<: *defaults
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Deploy to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master


  deploy_app_container_in_heroku:
    <<: *defaults
    steps:
      - setup_remote_docker:
          # Supported versions: https://circleci.com/docs/2.0/building-docker-images/#docker-version
          version: 20.10.6
      - checkout:
          path: ~/project
      - run:
          name: Build image
          command: |
            sudo curl https://cli-assets.heroku.com/install.sh | sh
            make build-ml-api-heroku
      - run:
          name: Push Image to Heroku
          command: |
            # Push the built container to the Heroku image registry
            make push-ml-api-heroku
      - run:
          name: Release to Heroku
          command: |
            make release-heroku

tags_only: &tags_only
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^.*/

workflows:
  version: 2
  section_07:
    jobs:
      - test_app
      - deploy_app_to_heroku:
          requires:
            - test_app
          filters:
            branches:
              only:
                - main
      - deploy_app_container_in_heroku:
          filters:
            branches:
              only:
                - main
